# -*- coding: utf-8 -*-
"""Ingalls_CruzCool_Production_Foam_Meta-Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OqgQF6IFnNV8ToW_lfW-PE22ELWGES-J
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import scipy as ss

df1 = pd.read_csv('/content/1. 632_1(L0823-BPC)(Box11)(RST)_20231009.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=1)
df2 = pd.read_csv('/content/2. 632_1(L0823-BPC)(Box10)(RST)_20231016.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=2)
df3 = pd.read_csv('/content/3. 632_1(L0823-BPC)(Box18)_20231018.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=3)
df4 = pd.read_csv('/content/4. 632_1(L0823-BPC)(Box16)(RST)_20231019.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=4)
df5 = pd.read_csv('/content/5. 632_1(0923-BPC)(Box9&Box15)_20231030.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=5)
df6 = pd.read_csv('/content/6. 632_1(L1023-BPC)(Box7OS)(Box4NS)_20231101.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=6)
df7 = pd.read_csv('/content/7. 632_1(Lot1023)(Box 4 & 5)_20231102.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=7)
df8 = pd.read_csv('/content/8. 632_1(0323-BPC)(Box08)(RST)20231114.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=8)
df9 = pd.read_csv('/content/9. 632_1(0923,0823)(Box5&12)_20231115.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=9)
df10 = pd.read_csv('/content/10. 632_1(Box#3)_20231120.xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=10)
df11 = pd.read_csv('/content/11. 632_1(L1023-BPC)(Box1)(OS).xlsx - CALCS.csv',na_values='#DIV/0!').assign(Trial=11)
dflist = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11]
#cdf = pd.merge(dflist).dropna()
#cdf.info()

"""Boxplot for Multiple Runs"""

# Pandas dataframe
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = [7.50, 3.50]
plt.rcParams["figure.autolayout"] = True

col = 'DENSITY [kg/m^3]'
##col = 'Thickness [inch]'
#col = 'Width [inch]'

data = pd.DataFrame({"10": df1[col], "11": df2[col], "16": df3[col], "18": df4[col],"9&15": df5[col], "7&4": df6[col],"4&5":df7[col],"8":df8[col]
                     ,"5&12":df9[col],"3":df10[col],"1":df11[col]}).dropna()
melt = pd.melt(data)

# Plot the dataframe
melt['value']=melt['value'].astype(float)

# Display the plot
sns.boxplot(x="variable", y="value", data=melt)
plt.xlabel('Box #')
plt.ylabel('Foam Density [kg/m^3]')
plt.title("Ingalls CruzCool Production(BPC Granules) - Foam Density by Box #")
plt.ylim(50,150)

plt.show()